# Usa a imagem oficial e mais recente do Alert Manager
FROM prom/alertmanager:latest

# Copia o seu arquivo de configuração customizado para o caminho padrão dentro do container
COPY config/alertmanager.yml /etc/alertmanager/alertmanager.yml
