# Usa a imagem oficial e mais recente do Prometheus
FROM prom/prometheus:latest

# Copia o arquivo de configuração customizado para o caminho padrão dentro do container
COPY config/prometheus.yml /etc/prometheus/prometheus.yml
