name: CI - Prometheus Configuration Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-config:
    runs-on: ubuntu-latest
    container:
      image: prom/prometheus:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Prometheus Config
        run: |
          # Valida todos os arquivos .yml do Prometheus
          cd prometheus/config/
          promtool check config prometheus.yml

# Validação de regras (por ora, vou deixar comentado)
#      - name: Validate Alertmanager Config
#        run: |
#          promtool check rules rules/*.yml

  validate-alertmanager:
    runs-on: ubuntu-latest
    container:
      image: prom/alertmanager:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Alertmanager Config
        run: |
          cd alertmanager/config/
          amtool check-config alertmanager.yml
