name: CI - Prometheus Configuration Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Prometheus Config
        run: |
          # Valida todos os arquivos .yml do Prometheus
          docker run --rm -v $(pwd):/work -w /work/prometheus/config \
          prom/prometheus:latest check config prometheus.yml

  validate-alertmanager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Alertmanager Config
        run: |
          docker run --rm -v $(pwd):/work -w /work/alertmanager/config \
          prom/alertmanager:latest check-config alertmanager.yml
